version: "3.9"

services:
  cripto:
    image: cripto
    environment:
      KEY: ${KEY}
      DB_URL: ${DB_URL}
      USER: ${DB_USER}
      PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
    command: ["java", "-jar", "cripto.jar"]
